### ISSUE TITLE
Cannot install using bower

### ISSUE THREAD

**Issue by enumag** [LPology/Simple-Ajax-Uploader#138]
I'm unable to install this package using bower because there are no tags in this repository. Can you fix it?

**Comment by enumag** [comment]
And npm for some reason thinks that 2.2.4 is the latest version of this package. https://www.npmjs.com/package/simple-ajax-uploader

**Comment by LPology** [comment]
@enumag What needs to be fixed with tags? I'm not very experienced with bower.

Also, I'm not sure why it's showing 2.2.4 in npm, or how to fix it. Do you know what needs to be done to update it?

**Comment by enumag** [comment]
Well the tags need to exist in the first place. Currently there are none. https://github.com/LPology/Simple-Ajax-Uploader/tags

As for NPM there is a wrong URL to the git repository. It seems the package was created by @ruanyl so maybe he can fix it?

**Comment by ruanyl** [comment]
Hi, I updated the npm package to the latest release. But I think the idea thing is both bower and npm packages are maintained by the repo maintainers. I created that npm package because I didn't find the package on npm and for some reason, I have to npm to manage the depens.

@enumag npm read the information from `package.json`, I will make a pull request to update the information.

**Comment by LPology** [comment]
@enumag I merged the pull request from @ruanyl to fix the `package.json` version number and URL. I also updated `bower.json` to use the full `2.4.0` version number.

Also, I created a tag for `2.4.0` and pushed it. @enumag , thanks for the info about git tags. I wasn't familiar with them before now, but I did some research and will begin using them now. 

Does this fix everything for this issue?

**Comment by enumag** [comment]
I believe so. I'll reopen it if I run into any issues.

By the way you might also check out github [releases](https://github.com/LPology/Simple-Ajax-Uploader/releases) feature. It's a great place for changelog.

**Comment by enumag** [comment]
Ok so bower unfortunately still doesn't work. The bower package is not linked to this repository but to a [fork](https://github.com/jenkinliang/Simple-Ajax-Uploader).

@jenkinliang Can you unregister your package from bower so that @LPology can do it himself properly?

**Comment by enumag** [comment]
@LPology Let's give him a week or so to reply. If he doesn't we can open a request in [bower/registry](https://github.com/bower/registry).

**Comment by LPology** [comment]
@enumag That works for me. Thanks for following up.

**Comment by enumag** [comment]
@LPology @ruanyl It works now. Thank you both for cooperation!
