### ISSUE TITLE
Upload URL always gets modified

### ISSUE THREAD

**Issue by hauru** [LPology/Simple-Ajax-Uploader#50]
Target URL always gets modified before the file upload. Even if there are no extra params specified, the file name is appended to the query string. This is problematic for platforms where an exact URL must be used - such as Google AppEngine. For GAE even appending "?" alone can cause problems.

I suggest adding a setting that would guarantee the URL to remain completely untouched. 

Thanks.

**Comment by dannycallaghan** [comment]
Hello. Has this been fixed by any chance? Really want to use your solution, we can't accept any params added to our URL.

**Comment by LPology** [comment]
@dannycallaghan 
Just pushed an update that adds a new `noParams` option. The default value is `false` to match previous behavior. 

To use an unaltered URL, set the `noParams` option to `true` and the value of the `url` option will be used without any modification.

**Comment by rwyland** [comment]
Hi I'm using version v2.0.1 and the ```noParams: true``` setting is not working for me.

Here is an example POST request sent when monitoring with Chrome Dev Tools, as you can see the filename is still getting attached as a URL param.


```
Request URL: https://mywebsite.com/upload?uploadfile=Sample.csv
Request Method: POST
Status Code: 302 Found
```

Any ideas? Cheers
